# Generated by Django 5.2.7 on 2025-11-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_ikiraro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='passportapplication',
            name='passport_type',
            field=models.CharField(choices=[('Ordinary Passport', 'Ordinary Passport'), ('Official Passport', 'Official Passport'), ('Diplomatic Passport', 'Diplomatic Passport'), ('Emergency Travel Document', 'Emergency Travel Document')], max_length=500),
        ),
    ]
