# Generated by Django 5.2.7 on 2025-11-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_ikiraro', '0003_passportapplication_current_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportapplication',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
